//
//  TrainSceneIntent.swift
//  Neuron
//
//  Created by Mac on 07.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//

import Combine
import SwiftUI

class TrainSceneIntent: ObservableObject {
    
    static let shared = TrainSceneIntent()
    
    private var neuron: Neuron!
    
    func setup() {
        neuron = Neuron()
    }
    
    func train(trainData: TrainScene.TrainData) {
        
    }
    
}
