//
//  TrainSceneView.swift
//  Neuron
//
//  Created by Mac on 07.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct TrainSceneView: View {
    
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var intent = TrainSceneIntent()
    
    var body: some View {
        ZStack {
            Text("TrainScene")
        }
        .onAppear {
            self.intent.setup()
        }
    }
    
}

struct TrainSceneView_Previews: PreviewProvider {
    static var previews: some View {
        TrainSceneView()
    }
}
